project: 
  type: website
  output-dir: "."
 
website:
  title: "lrwhiting"
  navbar:
    pinned: true
    left:
      - text: Project
        href: project.qmd
      - text: Blog
        href: blog-listing.qmd
      - text: R Basics
        href: danl-200-quarto.qmd
  page-footer: 
    center: "Powered with GitHub and Quarto<br>© lrwhiting, 2024"

format:
  html:
    theme: 
      light: journal
      dark: Vapor
      
    mainfont: system-ui; 
    highlight-style: atom-one
    css: styles.css
    toc: false
    include-after-body: target_blank.html
    
